project:
  type: website
  output-dir: docs
  resources:
  - "immagini/grid-ph.jpg"
  - "risorse/save_the_children_report-2023.pdf"
  - "CNAME"
  render:
  - "*.qmd"
  - "!note.md"

website:
  title: "Se lo vuoi sapere"
  site-url: https://selovuoisapere.it
  favicon: immagini/favico.png
  navbar:
    logo: immagini/logo_h.png
    left:
      - href: index.qmd
        text: Home
      - href: pubblicazioni/index.qmd
        text: Pubblicazioni
      - href: chi_sono.qmd
        text: Chi sono
      - about.qmd

  page-footer:
    border: false
    background: light
    center: |
      [Francesca Svanera](https://www.instagram.com/francesca_svanera/)

format:
  html:
    lang: "it-IT"
    theme:
      - cosmo
      - styles.scss
    css: styles.scss
    linkcolor: "#82baab"
    toc: true
    footnotes-hover: false
    citations-hover: false
    crossrefs-hover: false
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    link-external-filter: '^.*\.selovuoisapere\.it\/'
