project:
  type: website
  output-dir: docs
  resources: "immagini/grid-ph.jpg"
  render:
  - "*.qmd"
  - "!note.md"

website:
  title: "Se lo vuoi sapere"
  favicon: immagini/favico.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pubblicazioni/index.qmd
        text: Pubblicazioni
      - about.qmd

  page-footer:
    border: false
    background: light
    left: |
      Lorem ipsum
    right: |
      Hello
    center: |
      I'm in the middle

format:
  html:
    lang: "it-IT"
    theme:
      - cosmo
      - styles.scss
    css: styles.scss
    linkcolor: "#82baab"
    toc: true
    footnotes-hover: false
    citations-hover: false
    crossrefs-hover: false
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    link-external-filter: '^.*\.github\.io\/'
