project:
  type: website
  output-dir: docs

website:
  title: "Se-lo-vuoi-sapere"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    lang: "it-IT"
    theme:
      - cosmo
      - styles.scss
    css: styles.css
    toc: true
    footnotes-hover: false
    citations-hover: false
    crossrefs-hover: false
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    link-external-filter: '^.*\.github\.io\/'


execute:
  daemon: false
  freeze: auto
