project:
  type: website
  output-dir: docs

website:
  title: "Se-lo-vuoi-sapere"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - styles.scss
    css: styles.css
    toc: true



execute:
  daemon: false
  freeze: auto
